before:
  hooks:
    - go mod tidy
    - ginkgo -r
builds:
- env:
  - CGO_ENABLED=0
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    # Name of the built binary that should be used.
    # binary: goyaad
    # Templates of the Docker image names.
    image_templates:
    - "urjitbhatia/goyaad:latest"
    - "urjitbhatia/goyaad:v{{ .Major }}"
    - "urjitbhatia/goyaad:{{ .Tag }}"

    # Skips the docker push. Could be useful if you also do draft releases.
    # Defaults to false.
    skip_push: false

    # Path to the Dockerfile (from the project root).
    dockerfile: docker/goreleaser/Dockerfile

    # Template of the docker build flags.
    build_flag_templates:
    - "--label=version={{.Version}}"
    - "--build-arg=GOYAAD_VERSION={{.Version}}"
    # If Dockerfile copies files other than the binary itself,
    # you should list them here as well.
    # extra_files:
    # - config.yml