// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: chronomq.proto

package chronomq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job message matches the net/rpc Job
type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DelayMillis   int64                  `protobuf:"varint,2,opt,name=delay_millis,json=delayMillis,proto3" json:"delay_millis,omitempty"` // Delay in milliseconds
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_chronomq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetDelayMillis() int64 {
	if x != nil {
		return x.DelayMillis
	}
	return 0
}

func (x *Job) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PutWithIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutWithIDRequest) Reset() {
	*x = PutWithIDRequest{}
	mi := &file_chronomq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWithIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWithIDRequest) ProtoMessage() {}

func (x *PutWithIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWithIDRequest.ProtoReflect.Descriptor instead.
func (*PutWithIDRequest) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{1}
}

func (x *PutWithIDRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type PutWithIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutWithIDResponse) Reset() {
	*x = PutWithIDResponse{}
	mi := &file_chronomq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWithIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWithIDResponse) ProtoMessage() {}

func (x *PutWithIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWithIDResponse.ProtoReflect.Descriptor instead.
func (*PutWithIDResponse) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{2}
}

func (x *PutWithIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_chronomq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_chronomq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{4}
}

type NextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMillis int64                  `protobuf:"varint,1,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRequest) Reset() {
	*x = NextRequest{}
	mi := &file_chronomq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRequest) ProtoMessage() {}

func (x *NextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRequest.ProtoReflect.Descriptor instead.
func (*NextRequest) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{5}
}

func (x *NextRequest) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type NextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextResponse) Reset() {
	*x = NextResponse{}
	mi := &file_chronomq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextResponse) ProtoMessage() {}

func (x *NextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextResponse.ProtoReflect.Descriptor instead.
func (*NextResponse) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{6}
}

func (x *NextResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_chronomq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{7}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_chronomq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type InspectNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectNRequest) Reset() {
	*x = InspectNRequest{}
	mi := &file_chronomq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectNRequest) ProtoMessage() {}

func (x *InspectNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectNRequest.ProtoReflect.Descriptor instead.
func (*InspectNRequest) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{9}
}

func (x *InspectNRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type InspectNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectNResponse) Reset() {
	*x = InspectNResponse{}
	mi := &file_chronomq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectNResponse) ProtoMessage() {}

func (x *InspectNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chronomq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectNResponse.ProtoReflect.Descriptor instead.
func (*InspectNResponse) Descriptor() ([]byte, []int) {
	return file_chronomq_proto_rawDescGZIP(), []int{10}
}

func (x *InspectNResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_chronomq_proto protoreflect.FileDescriptor

const file_chronomq_proto_rawDesc = "" +
	"\n" +
	"\x0echronomq.proto\x12\bchronomq\"L\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdelay_millis\x18\x02 \x01(\x03R\vdelayMillis\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"3\n" +
	"\x10PutWithIDRequest\x12\x1f\n" +
	"\x03job\x18\x01 \x01(\v2\r.chronomq.JobR\x03job\"#\n" +
	"\x11PutWithIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rCancelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eCancelResponse\"4\n" +
	"\vNextRequest\x12%\n" +
	"\x0etimeout_millis\x18\x01 \x01(\x03R\rtimeoutMillis\"/\n" +
	"\fNextResponse\x12\x1f\n" +
	"\x03job\x18\x01 \x01(\v2\r.chronomq.JobR\x03job\"\r\n" +
	"\vPingRequest\"\"\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\x1f\n" +
	"\x0fInspectNRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\"5\n" +
	"\x10InspectNResponse\x12!\n" +
	"\x04jobs\x18\x01 \x03(\v2\r.chronomq.JobR\x04jobs2\xbe\x02\n" +
	"\bChronoMQ\x12D\n" +
	"\tPutWithID\x12\x1a.chronomq.PutWithIDRequest\x1a\x1b.chronomq.PutWithIDResponse\x12;\n" +
	"\x06Cancel\x12\x17.chronomq.CancelRequest\x1a\x18.chronomq.CancelResponse\x125\n" +
	"\x04Next\x12\x15.chronomq.NextRequest\x1a\x16.chronomq.NextResponse\x125\n" +
	"\x04Ping\x12\x15.chronomq.PingRequest\x1a\x16.chronomq.PingResponse\x12A\n" +
	"\bInspectN\x12\x19.chronomq.InspectNRequest\x1a\x1a.chronomq.InspectNResponseB0Z.github.com/chronomq/chronomq/api/grpc/chronomqb\x06proto3"

var (
	file_chronomq_proto_rawDescOnce sync.Once
	file_chronomq_proto_rawDescData []byte
)

func file_chronomq_proto_rawDescGZIP() []byte {
	file_chronomq_proto_rawDescOnce.Do(func() {
		file_chronomq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chronomq_proto_rawDesc), len(file_chronomq_proto_rawDesc)))
	})
	return file_chronomq_proto_rawDescData
}

var file_chronomq_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chronomq_proto_goTypes = []any{
	(*Job)(nil),               // 0: chronomq.Job
	(*PutWithIDRequest)(nil),  // 1: chronomq.PutWithIDRequest
	(*PutWithIDResponse)(nil), // 2: chronomq.PutWithIDResponse
	(*CancelRequest)(nil),     // 3: chronomq.CancelRequest
	(*CancelResponse)(nil),    // 4: chronomq.CancelResponse
	(*NextRequest)(nil),       // 5: chronomq.NextRequest
	(*NextResponse)(nil),      // 6: chronomq.NextResponse
	(*PingRequest)(nil),       // 7: chronomq.PingRequest
	(*PingResponse)(nil),      // 8: chronomq.PingResponse
	(*InspectNRequest)(nil),   // 9: chronomq.InspectNRequest
	(*InspectNResponse)(nil),  // 10: chronomq.InspectNResponse
}
var file_chronomq_proto_depIdxs = []int32{
	0,  // 0: chronomq.PutWithIDRequest.job:type_name -> chronomq.Job
	0,  // 1: chronomq.NextResponse.job:type_name -> chronomq.Job
	0,  // 2: chronomq.InspectNResponse.jobs:type_name -> chronomq.Job
	1,  // 3: chronomq.ChronoMQ.PutWithID:input_type -> chronomq.PutWithIDRequest
	3,  // 4: chronomq.ChronoMQ.Cancel:input_type -> chronomq.CancelRequest
	5,  // 5: chronomq.ChronoMQ.Next:input_type -> chronomq.NextRequest
	7,  // 6: chronomq.ChronoMQ.Ping:input_type -> chronomq.PingRequest
	9,  // 7: chronomq.ChronoMQ.InspectN:input_type -> chronomq.InspectNRequest
	2,  // 8: chronomq.ChronoMQ.PutWithID:output_type -> chronomq.PutWithIDResponse
	4,  // 9: chronomq.ChronoMQ.Cancel:output_type -> chronomq.CancelResponse
	6,  // 10: chronomq.ChronoMQ.Next:output_type -> chronomq.NextResponse
	8,  // 11: chronomq.ChronoMQ.Ping:output_type -> chronomq.PingResponse
	10, // 12: chronomq.ChronoMQ.InspectN:output_type -> chronomq.InspectNResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chronomq_proto_init() }
func file_chronomq_proto_init() {
	if File_chronomq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chronomq_proto_rawDesc), len(file_chronomq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chronomq_proto_goTypes,
		DependencyIndexes: file_chronomq_proto_depIdxs,
		MessageInfos:      file_chronomq_proto_msgTypes,
	}.Build()
	File_chronomq_proto = out.File
	file_chronomq_proto_goTypes = nil
	file_chronomq_proto_depIdxs = nil
}
