// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: chronomq.proto

package chronomq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChronoMQ_PutWithID_FullMethodName = "/chronomq.ChronoMQ/PutWithID"
	ChronoMQ_Cancel_FullMethodName    = "/chronomq.ChronoMQ/Cancel"
	ChronoMQ_Next_FullMethodName      = "/chronomq.ChronoMQ/Next"
	ChronoMQ_Ping_FullMethodName      = "/chronomq.ChronoMQ/Ping"
	ChronoMQ_InspectN_FullMethodName  = "/chronomq.ChronoMQ/InspectN"
)

// ChronoMQClient is the client API for ChronoMQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChronoMQClient interface {
	PutWithID(ctx context.Context, in *PutWithIDRequest, opts ...grpc.CallOption) (*PutWithIDResponse, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	InspectN(ctx context.Context, in *InspectNRequest, opts ...grpc.CallOption) (*InspectNResponse, error)
}

type chronoMQClient struct {
	cc grpc.ClientConnInterface
}

func NewChronoMQClient(cc grpc.ClientConnInterface) ChronoMQClient {
	return &chronoMQClient{cc}
}

func (c *chronoMQClient) PutWithID(ctx context.Context, in *PutWithIDRequest, opts ...grpc.CallOption) (*PutWithIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutWithIDResponse)
	err := c.cc.Invoke(ctx, ChronoMQ_PutWithID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoMQClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, ChronoMQ_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoMQClient) Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextResponse)
	err := c.cc.Invoke(ctx, ChronoMQ_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoMQClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ChronoMQ_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoMQClient) InspectN(ctx context.Context, in *InspectNRequest, opts ...grpc.CallOption) (*InspectNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectNResponse)
	err := c.cc.Invoke(ctx, ChronoMQ_InspectN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChronoMQServer is the server API for ChronoMQ service.
// All implementations must embed UnimplementedChronoMQServer
// for forward compatibility.
type ChronoMQServer interface {
	PutWithID(context.Context, *PutWithIDRequest) (*PutWithIDResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	Next(context.Context, *NextRequest) (*NextResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	InspectN(context.Context, *InspectNRequest) (*InspectNResponse, error)
	mustEmbedUnimplementedChronoMQServer()
}

// UnimplementedChronoMQServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChronoMQServer struct{}

func (UnimplementedChronoMQServer) PutWithID(context.Context, *PutWithIDRequest) (*PutWithIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutWithID not implemented")
}
func (UnimplementedChronoMQServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedChronoMQServer) Next(context.Context, *NextRequest) (*NextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedChronoMQServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedChronoMQServer) InspectN(context.Context, *InspectNRequest) (*InspectNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectN not implemented")
}
func (UnimplementedChronoMQServer) mustEmbedUnimplementedChronoMQServer() {}
func (UnimplementedChronoMQServer) testEmbeddedByValue()                  {}

// UnsafeChronoMQServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChronoMQServer will
// result in compilation errors.
type UnsafeChronoMQServer interface {
	mustEmbedUnimplementedChronoMQServer()
}

func RegisterChronoMQServer(s grpc.ServiceRegistrar, srv ChronoMQServer) {
	// If the following call pancis, it indicates UnimplementedChronoMQServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChronoMQ_ServiceDesc, srv)
}

func _ChronoMQ_PutWithID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutWithIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoMQServer).PutWithID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronoMQ_PutWithID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoMQServer).PutWithID(ctx, req.(*PutWithIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoMQ_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoMQServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronoMQ_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoMQServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoMQ_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoMQServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronoMQ_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoMQServer).Next(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoMQ_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoMQServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronoMQ_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoMQServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoMQ_InspectN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoMQServer).InspectN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronoMQ_InspectN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoMQServer).InspectN(ctx, req.(*InspectNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChronoMQ_ServiceDesc is the grpc.ServiceDesc for ChronoMQ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChronoMQ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chronomq.ChronoMQ",
	HandlerType: (*ChronoMQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutWithID",
			Handler:    _ChronoMQ_PutWithID_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _ChronoMQ_Cancel_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _ChronoMQ_Next_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ChronoMQ_Ping_Handler,
		},
		{
			MethodName: "InspectN",
			Handler:    _ChronoMQ_InspectN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chronomq.proto",
}
